### ISSUE TITLE
Non-UNIX line endings causes verification to fail

### ISSUE THREAD

**Issue by jeremyhill-up** [vkadam/grunt-jsbeautifier#43]
Firstly, love this plugin.  

JSBeautify specifications don't mention line endings, and as a point of reference, other tools such as HTML/JS/CSS Beautify in Sublime Text don't care about line endings.  However, this plugin will fail verification if the line endings are not UNIX formatted, even if the files are otherwise identically formatted to other tools that format using JSBeautify.

**Comment by vkadam** [comment]
I have pushed a fix in version 0.2.9, see #45 & #46 Let me know if this does fix for you.

**Comment by Odi55555** [comment]
Unfortunately this didn't fix it. 
If you have an formatted js file with UNIX line endings (LF) and run the jsbeautifier task everything is fine. But if you change the line endings to Windows (CR LF) und run the task again, it will change the line endings back to LF. 
This causes uncommited changes in git, but git will ignore the changes if you try to stage them. IntelliJ on Windows also has problems with that and shows all "beautified" files as changed.
Do you what causes the line endings change?
Thx for your help.

**Comment by chris-gunawardena** [comment]
Having the same issue on Windows, our git is setup to checkout with Windows line endings and commit back with Unix line endings. All the files come up as changed on git even when no changes are made. This is preventing us from using this as a part of our workflow, Maybe we should log this in https://github.com/beautify-web/js-beautify ?

**Comment by vkadam** [comment]
There is a bug open in https://github.com/beautify-web/js-beautify/issues/260

I am also doing new line check in this plugin but its only for back compatibility. This check in plugin was added when new line support from js-beautify was limited.

**Comment by sethflowers** [comment]
+1 - facing the same issue with git... we can't use the plugin as is. It doesn't look like there is any traction on the referenced open js-beautify issue from almost a year and a half ago.

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/issues/260 ...  Fixed.

**Comment by vkadam** [comment]
@Everyone,
First of all apologies for not following up on this. But looks like js-beautify bug is fixed. Will you please check and confirm if that fixed the issue for you as well. If it does then report here so I can close the ticket.

Thanks a lot in advance.

**Comment by vkadam** [comment]
Not heard for long back, hope issue is fixed so closing ticket. If this issue still persist, please open new bug.
